using System.Text.Json.Serialization;

namespace L2Config.Core.Catalog;

/// <summary>The friendly layer over every editable value, generated by catalog/build_catalog.py.</summary>
public sealed class SettingsCatalog
{
	public int Version { get; init; }
	public IReadOnlyList<CategoryDefinition> Categories { get; init; } = [];
	public IReadOnlyList<SettingDefinition> Settings { get; init; } = [];
}

public sealed class CategoryDefinition
{
	public required string Id { get; init; }
	public required string Name { get; init; }
	public string Glyph { get; init; } = "";

	/// <summary>"server" or "client".</summary>
	public string Scope { get; init; } = "server";

	public string Description { get; init; } = "";
	public IReadOnlyList<GroupDefinition> Groups { get; init; } = [];
}

public sealed class GroupDefinition
{
	public required string Id { get; init; }
	public required string Name { get; init; }
}

public sealed class SettingDefinition
{
	public required string Id { get; init; }

	/// <summary>Which store owns the value: server-game, server-login, client-option, client-l2ini, world-profile.</summary>
	public required string Target { get; init; }

	/// <summary>File name relative to the target's folder (for server targets, relative to config/).</summary>
	public required string File { get; init; }

	/// <summary>INI section for sectioned client files; null for the section-less server files.</summary>
	public string? Section { get; init; }

	public required string Key { get; init; }
	public required string Category { get; init; }
	public required string Group { get; init; }
	public required string Name { get; init; }
	public string Description { get; init; } = "";
	public SettingEditor Editor { get; init; } = SettingEditor.Text;
	public SettingValueType ValueType { get; init; } = SettingValueType.String;
	public IReadOnlyList<string>? Options { get; init; }
	public string? Unit { get; init; }
	public double? Min { get; init; }
	public double? Max { get; init; }

	/// <summary>Shape a text value must have (int-list, pair-list, hex-color, time-list, …); see SettingValues.</summary>
	public string? Format { get; init; }
	public string? Default { get; init; }
	public string? ShippedValue { get; init; }
	public bool Advanced { get; init; }
	public string? ManagedReason { get; init; }
	public bool Secret { get; init; }

	[JsonPropertyName("l2everdream")]
	public bool L2Everdream { get; init; }

	[JsonIgnore]
	public bool IsManaged => !string.IsNullOrEmpty(ManagedReason);
}

[JsonConverter(typeof(JsonStringEnumConverter<SettingEditor>))]
public enum SettingEditor
{
	[JsonStringEnumMemberName("text")] Text,
	[JsonStringEnumMemberName("list")] List,
	[JsonStringEnumMemberName("number")] Number,
	[JsonStringEnumMemberName("slider")] Slider,
	[JsonStringEnumMemberName("toggle")] Toggle,
	[JsonStringEnumMemberName("choice")] Choice,
	[JsonStringEnumMemberName("secret")] Secret,
}

[JsonConverter(typeof(JsonStringEnumConverter<SettingValueType>))]
public enum SettingValueType
{
	[JsonStringEnumMemberName("string")] String,
	[JsonStringEnumMemberName("int")] Int,
	[JsonStringEnumMemberName("decimal")] Decimal,
	[JsonStringEnumMemberName("bool")] Bool,
}

public static class SettingTargets
{
	public const string ServerGame = "server-game";
	public const string ServerLogin = "server-login";
	public const string ClientOption = "client-option";
	public const string ClientL2Ini = "client-l2ini";
	public const string WorldProfile = "world-profile";

	public static bool IsClient(string target) => target.StartsWith("client-", StringComparison.Ordinal);
}
